### ISSUE TITLE
Windows Build Environment

### ISSUE THREAD

**Issue by NHALX** [tizoc/shen-scheme#10]
Would be good if the readme described the expected windows build environment a bit more.

**Comment by tizoc** [comment]
Agree, will do. I don't remember exactly right now the setup, I have to relaunch the EC2 instance with Windows 10 that I used to build the Windows releases, but I think all I had to install was Visual Studio and msys2 (along with some dependencies like git).

**Comment by NHALX** [comment]
VisualStudio2017 and the following packages seemed to do it:

 pacman -Sy
 pacman -S mingw-w64-x86_64-gcc
 pacman -S mingw-w64-x86_64-gdb
 pacman -S git
 pacman -S make
 pacman -S curl

curl and tar were broken in my fresh install of msys2. The build worked fine by downloading and unpacking Chez with other methods though.

**Comment by tizoc** [comment]
Listed dependencies here: https://github.com/tizoc/shen-scheme/commit/113f7a3ee4969824d7c4ab71d2233f6516f1dce7#diff-04c6e90faac2675aa89e2176d2eec7d8R65

Now every new release gets binaries built automatically with Travis (this includes Windows).
