### ISSUE TITLE
Build error on linux

### ISSUE THREAD

**Issue by doug719** [tizoc/shen-scheme#15]
I am using linux mint 20.0.  On April 26, 2021 I downloaded the source and did a make, and got the following:

"
main.c:66:5: note: ‘snprintf’ output between 11 and 4106 bytes into a destination of size 4096
   66 |     snprintf(shen_scheme_bootfile_path, PATH_MAX, "%s%sshen.boot",
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   67 |              shen_scheme_home_path,PATH_SEPARATOR);
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mkdir -p _build/bin
cc -o _build/bin/shen-scheme _build/chez/csv9.5.4/ta6le/boot/ta6le/kernel.o main.o -lm -ldl -lpthread -luuid
make: *** No rule to make target 'shen-scheme.scm', needed by '_build/lib/shen-scheme/shen.boot'.  Stop.

"
I downloaded a binary version, which worked fine, and was very fast.

**Comment by tizoc** [comment]
When you say that you downloaded the source, you mean one of the `-src.tar.gz` release files in https://github.com/tizoc/shen-scheme/releases or by cloning the repo? You should use one of those.

If you clone the repository instead, there are a few extra steps: https://github.com/tizoc/shen-scheme#building-from-scratch

**Comment by doug719** [comment]
I downloaded
shen-scheme-v0.24-src.tar.gz

and did a 

make prefix=/opt/shen-scheme
after a tar command.  Note that I am using linux mint 20.0.



Regards,Doug



    On Tuesday, April 27, 2021, 8:38:45 AM MDT, Bruno Deferrari ***@***.***> wrote:  
 
 


When you say that you downloaded the source, you mean one of the -src.tar.gz release files in https://github.com/tizoc/shen-scheme/releases or by cloning the repo? You should use one of those.

If you clone the repository instead, there are a few extra steps: https://github.com/tizoc/shen-scheme#building-from-scratch

**Comment by tizoc** [comment]
I see. Looks like there is a bug on the CI script that produces the source release tarball and it is adding an extra nesting to the precompiled files directory, try doing this and run make again:

```
mv compiled/compiled/* compiled/
```

**Comment by doug719** [comment]
Hello Bruno,
Your changes fixed the problem.
Regards,Doug

    On Tuesday, April 27, 2021, 9:54:07 AM MDT, Bruno Deferrari ***@***.***> wrote:  
 
 


I see. Looks like there is a bug on the CI script that produces the source release tarball and it is adding an extra nesting to the precompiled files directory, try doing this and run make again:
mv compiled/compiled/* compiled/

**Comment by tizoc** [comment]
Fixed the script and updated shen-scheme-v0.24-src.tar.gz with a version containing the precompiled in the right place, thanks for the report. Closing.
