### ISSUE TITLE
intel mac support

### ISSUE THREAD

**Issue by joelmccracken** [tizoc/shen-scheme#28]
Hi, I decided to try the shen scheme implementation again, and I ran across an issue (is it the one I had before? I can't remember):

```
> tar xvzf shen-scheme-v0.38-macOS-bin.tar.gz
> cd shen-scheme-v0.38-macOS-bin
> bin/shen-scheme
zsh: bad CPU type in executable: bin/shen-scheme
[127]> file bin/shen-scheme 
bin/shen-scheme: Mach-O 64-bit executable arm64 
```
A little while back github switched their default runners to use arm by default; you can specify a specific version (ideally add it so both intel and arm versions are built) like here: https://github.com/joelmccracken/workstation/blob/master/.github/workflows/test.yml#L22-L28

I guess this will necessitate changing how releases are done, I haven't looked at that yet.

**Comment by tizoc** [comment]
Good catch, will fix this soon. Thank you!

**Comment by joelmccracken** [comment]
Thank you! 

Something you may want to do as well: its common now to run arm linux on arm macs in docker, so in case someone wanted to use shen in docker and download the binaries provided here, they would have issues. Just a thought that came to me

**Comment by joelmccracken** [comment]
oh nevermind, it seems that perhaps github doesnt have runners for that. nevermind!
