### ISSUE TITLE
Chibi 0.7.3 repl fails

### ISSUE THREAD

**Issue by raould** [tizoc/shen-scheme#3]
I know you wrote that it works with 0.7. I am not sure if the delta to 0.7.3 is the root cause. Anybody else use other versions? 0.7.3 is current git master for Chibi, I think.

$ chibi-scheme -Rshen.runner
ERROR on line 3 of file ./shen/compiled/types.kl.scm: undefined variable: shen.parameters

(I'm on Ubuntu 14.04 x86, if it matters any.)

**Comment by raould** [comment]
Never mind. Must have been a screwed up build (my laptop battery did die recently). When I did "make" it told me there was nothing to do, and I got the error above with it. But then now I did "make clean" and a "make" and now it works.

**Comment by tizoc** [comment]
Well, chibi-scheme 0.7.3 has not been released yet, but good to know that so far nothing breaks compared to 0.7.2.

**Comment by raould** [comment]
Sorry to be thrashing here. There's something odd where the first run of Make results in a version that fails. Then if I do make clean && make, it seems to end up with a build that works. I haven't experimented enough to see exactly what is going on. Just wanted to report fyi.

```
$ chibi-scheme -Rshen.runner
WARNING: reference to undefined variable: kl:destroy
WARNING: reference to undefined variable: kl:package
WARNING: reference to undefined variable: kl:receive
WARNING: reference to undefined variable: kl:shen.typecheck-and-evaluate
WARNING: reference to undefined variable: kl:shen.prefix?
WARNING: reference to undefined variable: kl:shen.newline
WARNING: reference to undefined variable: kl:shen.carriage-return
WARNING: reference to undefined variable: kl:shen.hat
WARNING: reference to undefined variable: kl:tc
WARNING: importing undefined variable: kl:shen.shen
WARNING: reference to undefined variable: kl:shen.shen
ERROR in main on line 10 of file ./shen/runner.sld: undefined variable: kl:shen.shen
Searching for modules exporting kl:shen.shen ...
kl:shen.shen is exported by:
  (shen init)
```

**Comment by tizoc** [comment]
I wasn't able to reproduce this.

Does this always happen? Or is this something that happened just once?

All those undefined variables come from the Shen sources, but if one of the files were missing the error would be different. My guess here is that when generating one of the Scheme files form the KLambda sources an interruption caused one of the files to not be fully generated (this creating the file allowing the runner to start, but having some variables missing).
